### ISSUE TITLE
Caching of tiles

### ISSUE THREAD

**Issue by peteralt** [dhoerl/PhotoScrollerNetwork#27]
Wonderful work, this is a great extension of the existing example from Apple.
I'm working on a browser for high-res images, but these images are not dynamic, so I would be totally happy with pre-tiling offline (or within the app once and keep the tiled images on the device). Looking through the code, I wasn't really able to identify where I would need to implement that feature.

Correct me if my understanding is wrong: 
Right now the tiles are generated and only the reference is kept in the system, while the actual file has already been deleted (UNIX trick). So in order to be able to cache the tiles, I would have to remove that function and before generating the tiles, I would have to check if the files are already in the tmp folder.

Thanks!

**Comment by dhoerlST** [comment]
If you are not going to try and in real time download large images and show them, then you should be able to use PhotoScroller as is. In that case you would pre-tile the images in the cloud, and download them singly or as an archive. This will save you some space too, as Apple has each tile as a JPEG where as this project saves the data as RGBA. Several people have developed code that will take a large image and generate all the various tile images (some large images will have 600 or so tiles as I recall). Even with libjpeg-turbo, the tiling consumes an awful lot of processing power...

**Comment by jerday** [comment]
Was looking for a similar answer and tried switching to Apple's version, but damn those tiles add a lot of application bloat. I'd prefer to just force the user to wait and use your solution (since it means a single 6.1MB image vs 70MB in tiles. However, will the image tiles be cached for next display / app launch? This is unclear from your demo.

**Comment by peteralt** [comment]
That's the one feature I'd love to see. Caching would be a great solution for us.
@dhoerlST I'm happy to implement some caching on my own, would you be able to point me towards where to do that?

**Comment by dhoerl** [comment]
Jerday, if you think 70Meg is big, you are wrong - those Apple tiles are the multitude of jpeg images. What this framework does is render each pixel as a full 32 bit quantity. It makes it fast to view images, but  if you go save each one its going to be huge! Its not just the full sized image that is rendered - its each size reduction to - each pixel. So you can do the math on our 6.1M jpeg (you didn't give the dimensions). My recollection in testing large images is that they consumed well over 100Meg of file space. The sole purpose of this project was to allow an app to download and decompress in real time, since often the decompression of a downloaded image would double the time before a user could see an image, and since the decompression on multicore devices meant you hardly impacted the UI at all.

**Comment by jerday** [comment]
It's big in the sense that I can't have my app over the 100MB limit, as a business requirement. Saving to disk after tiling is no problem, if we modified to cache the tiles.

**Comment by dhoerl** [comment]
I'll look at it this weekend.

**Comment by dhoerl** [comment]
I just didn't get to it - kitchen torn apart while renovating it (myself). Commitment Monday night too. Will try to make some time during the week to figure it all out. There are two issues: first, separating out the construction of the file so it can be saved, then the development of a UI to show the saved image from the file itself. My plan would be to create two new apps, one to save, the other to read and show.

**Comment by dhoerl** [comment]
I just updated some changes to the project. I added a text file telling you how I would approach archiving (saving) and image, and then later restoring it. It took me a few hours just to tell you how to do it - expect a few days of playing around with crashes to get it working. I just didn't design it for that purpose. Feel free to ask questions on this thread as you progress. Use the latest source I just uploaded - I made a few changes to help you in the process.

**Comment by peteralt** [comment]
Thanks a lot, David! I'll take a look at your edits! Hope the kitchen is back in order :)

**Comment by dhoerl** [comment]
FYI - in the process of turning this project into a Swift Package, and this will be the first new addition.

**Comment by dhoerl** [comment]
Swift Package done!
