### ISSUE TITLE
What kind of license this project has?

### ISSUE THREAD

**Issue by Ponf** [dhoerl/PhotoScrollerNetwork#28]
First of all, thank you so much for a such great component!

Could you please provide a license information in README.txt or LICENSE file to make it legal to use this library in our application?

**Comment by dhoerl** [comment]
In all fairness the source code has a license on a per file basis:

*
 * Redistribution and use in source and binary forms, with or without modification, are
 * permitted provided that the following conditions are met:
 *
 *    1. Redistributions of source code must retain the above copyright notice, this list of
 *       conditions and the following disclaimer.
 *
 *    2. Redistributions in binary form must reproduce the above copyright notice, this list
 *       of conditions and the following disclaimer in the documentation and/or other materials
 *       provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY David Hoerl ''AS IS'' AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
 * FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL David Hoerl OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

But good point - I'll add one..

**Comment by dhoerl** [comment]
On 4/8/15 10:17 AM, Filipp Panfilov wrote:
> First of all, thank you so much for a such great component!
>
> Could you please provide a license information in README.txt or LICENSE
> file to make it legal to use this library in our application?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dhoerl/PhotoScrollerNetwork/issues/28>.
>
Done

**Comment by Ponf** [comment]
Thanks!
